from datetime import datetime

def generate_report(damage_type, severity, image_name):

    # ---------------------------
    # RECOMMENDATION LOGIC
    # ---------------------------
    if severity == "Minor":
        recommendation = "Minor issue detected. Regular monitoring is advised."

    elif severity == "Moderate":
        recommendation = "Moderate damage detected. Maintenance is recommended."

    elif severity == "Severe":
        recommendation = "Severe damage detected. Immediate repair is required."

    else:
        recommendation = "No damage detected. No action required."

    # ---------------------------
    # REPORT FORMAT
    # ---------------------------
    report = f"""
==============================
   BUILDING DAMAGE REPORT
==============================

Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

--------------------------------
Image Analyzed : {image_name}
Damage Type    : {damage_type}
Severity Level : {severity}
--------------------------------

Recommendation:
{recommendation}

--------------------------------
Generated by AI Snag Detection System
"""

    return report